
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class TaxCalculatorTest {
  @Test
  public void testSumMethod() {
    TaxCalculator calc = new TaxCalculator();
    assertTrue("First java test", calc.sum(2, 3) > 1);
  }

  //@Test
  public void testFailSumMethod() {
    TaxCalculator calc = new TaxCalculator();
    assertTrue("Try failing", calc.sum(2, 3) < 1);
  }
}
